version: '3.7'

services:
    composer:
        image: composer:latest
        volumes:
            - ./:/app
        working_dir: /app
        entrypoint: ["composer", "install", "--ignore-platform-reqs"]
    
    php:
        build:
            context: ./infra
            dockerfile: php.Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - 8080:80
        depends_on:
            - composer
        command: php -S

    migrate:
        build:
            context: ./infra/php.Dockerfile
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - composer
        command: php artisan migrate