version: '3.7'

services:
    composer:
        image: composer:latest
        volumes:
            - ./:/app
        working_dir: /app
        entrypoint: ["composer", "install", "--ignore-platform-reqs"]

    passport:
        build:
            context: .
            dockerfile: ./infra/php.Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - composer
        entrypoint: ["sh", "-c", "php artisan passport:install && php artisan passport:key --force"]

    migrate:
        build:
            context: .
            dockerfile: ./infra/php.Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - passport
        entrypoint: ["sh", "-c", "php artisan migrate"]

    php:
        build:
            context: .
            dockerfile: ./infra/php.Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80
        depends_on:
            - mysql
            - migrate
        command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=80"]

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5


volumes:
    db_data: {}